spring:
    application:
        name: googleAuthorization
    profiles:
        active: dev
---
spring: 
    config:
        activate: 
            on-profile: dev


logging:
  file:
    name: ~/logs/googleAuth.log
  level:
    '[org.springframework]': INFO
    '[com.demo]': INFO